/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareIndexRouteImport } from './routes/compare.index'
import { Route as CompareIsmileDentalSoftwareRouteImport } from './routes/compare.ismile-dental-software'
import { Route as CompareDentallyRouteImport } from './routes/compare.dentally'
import { Route as ApiPublicVerifyWaitlistSignupRouteImport } from './routes/api/public/verify-waitlist-signup'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIsmileDentalSoftwareRoute =
  CompareIsmileDentalSoftwareRouteImport.update({
    id: '/compare/ismile-dental-software',
    path: '/compare/ismile-dental-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareDentallyRoute = CompareDentallyRouteImport.update({
  id: '/compare/dentally',
  path: '/compare/dentally',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifyWaitlistSignupRoute =
  ApiPublicVerifyWaitlistSignupRouteImport.update({
    id: '/api/public/verify-waitlist-signup',
    path: '/api/public/verify-waitlist-signup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/compare/dentally': typeof CompareDentallyRoute
  '/compare/ismile-dental-software': typeof CompareIsmileDentalSoftwareRoute
  '/compare/': typeof CompareIndexRoute
  '/api/public/verify-waitlist-signup': typeof ApiPublicVerifyWaitlistSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/compare/dentally': typeof CompareDentallyRoute
  '/compare/ismile-dental-software': typeof CompareIsmileDentalSoftwareRoute
  '/compare': typeof CompareIndexRoute
  '/api/public/verify-waitlist-signup': typeof ApiPublicVerifyWaitlistSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/compare/dentally': typeof CompareDentallyRoute
  '/compare/ismile-dental-software': typeof CompareIsmileDentalSoftwareRoute
  '/compare/': typeof CompareIndexRoute
  '/api/public/verify-waitlist-signup': typeof ApiPublicVerifyWaitlistSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/waitlist'
    | '/compare/dentally'
    | '/compare/ismile-dental-software'
    | '/compare/'
    | '/api/public/verify-waitlist-signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/waitlist'
    | '/compare/dentally'
    | '/compare/ismile-dental-software'
    | '/compare'
    | '/api/public/verify-waitlist-signup'
  id:
    | '__root__'
    | '/'
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/waitlist'
    | '/compare/dentally'
    | '/compare/ismile-dental-software'
    | '/compare/'
    | '/api/public/verify-waitlist-signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiesRoute: typeof CookiesRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  WaitlistRoute: typeof WaitlistRoute
  CompareDentallyRoute: typeof CompareDentallyRoute
  CompareIsmileDentalSoftwareRoute: typeof CompareIsmileDentalSoftwareRoute
  CompareIndexRoute: typeof CompareIndexRoute
  ApiPublicVerifyWaitlistSignupRoute: typeof ApiPublicVerifyWaitlistSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/ismile-dental-software': {
      id: '/compare/ismile-dental-software'
      path: '/compare/ismile-dental-software'
      fullPath: '/compare/ismile-dental-software'
      preLoaderRoute: typeof CompareIsmileDentalSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/dentally': {
      id: '/compare/dentally'
      path: '/compare/dentally'
      fullPath: '/compare/dentally'
      preLoaderRoute: typeof CompareDentallyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify-waitlist-signup': {
      id: '/api/public/verify-waitlist-signup'
      path: '/api/public/verify-waitlist-signup'
      fullPath: '/api/public/verify-waitlist-signup'
      preLoaderRoute: typeof ApiPublicVerifyWaitlistSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiesRoute: CookiesRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  WaitlistRoute: WaitlistRoute,
  CompareDentallyRoute: CompareDentallyRoute,
  CompareIsmileDentalSoftwareRoute: CompareIsmileDentalSoftwareRoute,
  CompareIndexRoute: CompareIndexRoute,
  ApiPublicVerifyWaitlistSignupRoute: ApiPublicVerifyWaitlistSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
